### PR TITLE
Updated Devlog

### PR DESCRIPTION
**Pull request by WW-Web-Infra**
@auremoser I have updated the Devlog with the latest status!! Unfortunately, I am not aware of the syntax to display it in the new line (GSOC-Dev). Can you please review it?! :dancer:

### CODE REVIEW

**Review by auremoser — APPROVED** [review]
Looks great, thank you so much!

**Comment by WW-Web-Infra** [comment]
@auremoser Thank you!!

**Comment by auremoser** [comment]
Revisited this and realized you asked about  the syntax for a new line, do you mean in the `posts` directory? (you can just add a `<br/>` tag wherever you'd like a hard return and it will add one. 

If you meant elsewhere (not in the _posts, but a line break somewhere else, please let me know and I'll help.

**Comment by WW-Web-Infra** [comment]
@auremoser thank you so much!!

**Pull request merged**
