### PR TITLE
Dashboard code review

### PR DESCRIPTION
**Pull request by WW-Web-Infra**
The Study Group Dashboard is inspired by [Gentelella](https://github.com/puikinsh/gentelella)!! 
The Dashboard comprises of statistics from json data. The statistics are collected from [sg-events](https://github.com/auremoser/sg-events).

Description:
1) "Total" tags are static (dynamic version yet to complete).
2) Download the files and add the full path of Data/*.json to js/Dashboard.js. If the full path is not mentioned, we may face [Access to restricted URI denied](https://stackoverflow.com/questions/26805093/dynamic-directive-loading-using-angularjs-error-access-to-restricted-uri-deni) issue.
3) Click on index3.js. Grab on Mozilla Study Group Dashboard!!

Please give feedback! Cheers!

### CODE REVIEW

**Comment by WW-Web-Infra** [comment]
@auremoser Check this out!!!

**Comment by auremoser** [comment]
Very cool, I like the little graphs and it's a great prototype!

Two questions:
* where does the dummy data come from?
* do you think we can merge this with the [study group events site](https://mozillascience.github.io/studyGroupEvents/)?

Great work, well done!

**Comment by WW-Web-Infra** [comment]
@auremoser Thank you for the review! <3
1) The dummy data is a random data, fetching correct data is incomplete.
2) Yes we can!! We can add the link to [Study Group Event](https://mozillascience.github.io/studyGroupEvents/). We need to check that dashboard.js can access the  JSON data. I will polish the site and may be add one or two graphs :) 
By the end of this week, we can merge this 💃

**Comment by auremoser** [comment]
Very exciting @AnamikaD ! Thank you for all your hard work!

**Comment by WW-Web-Infra** [comment]
Thank you @auremoser ! All this because of your guide and motivation :D

**Pull request merged**
